### ISSUE TITLE
pyaudio and playsound

### ISSUE THREAD

**Issue by oatmealm** [jkitchin/litdb#1]
Hi there! Was wondering, are these two libraries essential? I've spent an hour to figure out why they won't install and it turns out that at least playound needs to v 12.2 since 1.3.0 won't install. Some other issue with pyaudio I'm still trying to figure out (it's being build locally and missing portauio.h).

On Fedora 41, using uvx

```
 uvx --with playsound==1.2.2 --from git+https://github.com/jkitchin/litdb litdb  --version
```

Solved with: ` sudo dnf install portaudio-devel` 

Thanks!

**Comment by jkitchin** [comment]
It is not essential. Those are used in the audio subcommand where you can speak your query, transcribe it to text, and then search with that. I commented out the libraries in pyproject. I think they are only imported in the audio functions, so it shouldn't cause any issues if you don't use them. I didn't find the transcription to be that good, especially for scientific terms, so it isn't a function i use a lot.

**Comment by oatmealm** [comment]
I didn't get to the voice transcription section yet  ... was too excited about the basic premise of this lib as is :) ...
